---
services:
  transformers-notebook:
        build: ./
        ports: 
            - 8000:8888
        environment:
            - JUPYTER_TOKEN=visa-exam-maa
        volumes:
            - ./:/home/jovyan               
...